"""crc16-xmodem -- XMODEM, ZMODEM, ACORN, LTE

Parameters: width=16, poly=0x1021, init=0x0000, refin=false, refout=false, xorout=0x0000.
check: crc16_xmodem(data) over "123456789" == 0x31C3

Example:
    Streaming -- call init, then update over each chunk, then finalize::

        s = crc16_xmodem_init()
        s = crc16_xmodem_update(s, chunk)  # over each chunk of the message
        crc = crc16_xmodem_finalize(s)

    One-shot: crc16_xmodem(data)

Note:
    Verify with crc16_xmodem_self_test() (returns True on success); run it once on your interpreter to catch a build / width mismatch.
    Generated by crcglot from reveng/crc16-xmodem -- a verified reference implementation.
"""


def crc16_xmodem_init() -> int:
    """Return the initial CRC state to begin a computation.

    Returns:
        the starting int state.
    """
    return 0x0000


def crc16_xmodem_update(state: int, data: bytes) -> int:
    """Fold input into the running CRC state and return the new state.

    Args:
        state: running int state (from init or a prior update).
        data: the message bytes (a bytes-like object).

    Returns:
        the updated int state (not yet finalized).

    Note:
        Call init -> update (any number of times) -> finalize.
    """
    crc = state
    for byte in data:
        crc ^= byte << 8
        for _ in range(8):
            if crc & 0x8000:
                crc = (crc << 1) ^ 0x1021
            else:
                crc <<= 1
            crc &= 0xFFFF
    return crc


def crc16_xmodem_finalize(state: int) -> int:
    """Return the finished CRC; this algorithm applies no final transform.

    Args:
        state: accumulated int state from update.

    Returns:
        the finished CRC value.

    Note:
        Do not feed the finalized value back into update.
    """
    return state


def crc16_xmodem(data: bytes) -> int:
    """One-shot convenience: init + a single update + finalize.

    Args:
        data: the message bytes (a bytes-like object).

    Returns:
        the finished CRC value.
    """
    state = crc16_xmodem_init()
    state = crc16_xmodem_update(state, data)
    return crc16_xmodem_finalize(state)


def crc16_xmodem_self_test() -> bool:
    """Self-test the implementation against independent reference CRCs.

    Returns:
        True iff the generated CRC reproduces every embedded reference value.

    Note:
        Catalogue algorithms check four fixed inputs (the empty string, "123456789", all 256 byte values, and a 1 KiB pattern); the two large inputs are regenerated with a byte-at-a-time loop, so no big array is embedded.  The references come from two independent engines that had to agree.
        Run once on your target toolchain -- it is the cheapest way to catch a compiler / endianness / width mismatch before trusting the output.
    """
    if crc16_xmodem(b"") != 0x0000:
        return False
    if crc16_xmodem(b"123456789") != 0x31C3:
        return False
    s = crc16_xmodem_init()
    for i in range(256):
        s = crc16_xmodem_update(s, bytes([i]))
    if crc16_xmodem_finalize(s) != 0x7E55:
        return False
    s = crc16_xmodem_init()
    for i in range(1024):
        s = crc16_xmodem_update(s, bytes([(i * 167 + 13) & 0xFF]))
    if crc16_xmodem_finalize(s) != 0x97E5:
        return False
    return True
