/* crc16-xmodem -- XMODEM, ZMODEM, ACORN, LTE
 * Parameters: width=16, poly=0x1021, init=0x0000, refin=false, refout=false, xorout=0x0000.
 * check: crc16_xmodem(data, len) over "123456789" == 0x31C3
 *
 * Streaming (init -> update -> finalize); update may be called any
 * number of times over successive chunks of the message:
 *
 *     uint16_t s = crc16_xmodem_init();
 *     s = crc16_xmodem_update(s, chunk, chunk_len);
 *     uint16_t crc = crc16_xmodem_finalize(s);
 *
 * One-shot: crc16_xmodem(data, len)
 * Verify:   crc16_xmodem_self_test() returns 0 on success; run it once on your
 *           toolchain to catch a compiler / endianness mismatch.
 *
 * Generated by crcglot from reveng/crc16-xmodem -- a verified reference implementation.
 * Reproduce with crcglot:
 *     algorithm: crc16-xmodem
 *     target:    c
 *     variant:   bitwise
 *     comment:   plain
 *     symbol:    crc16_xmodem
 *     naming:    snake
 */
#ifndef CRC16_XMODEM_H
#define CRC16_XMODEM_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Return the initial CRC state to begin a computation.
 *
 * Returns the starting uint16_t state.
 */
uint16_t crc16_xmodem_init(void);

/* Fold input into the running CRC state and return the new state.
 *
 * state: running uint16_t state (from init or a prior update).
 * data: pointer to the message bytes.
 * len: number of bytes available at data.
 *
 * Returns the updated uint16_t state (not yet finalized).
 *
 * Call init -> update (any number of times) -> finalize.
 */
uint16_t crc16_xmodem_update(uint16_t state, const uint8_t *data, size_t len);

/* Return the finished CRC; this algorithm applies no final transform.
 *
 * state: accumulated uint16_t state from update.
 *
 * Returns the finished CRC value.
 *
 * Do not feed the finalized value back into update.
 */
uint16_t crc16_xmodem_finalize(uint16_t state);

/* One-shot convenience: init + a single update + finalize.
 *
 * data: pointer to the message bytes.
 * len: number of bytes available at data.
 *
 * Returns the finished CRC value.
 */
uint16_t crc16_xmodem(const uint8_t *data, size_t len);

/* Self-test the implementation against independent reference CRCs.
 *
 * Returns 0 iff the generated CRC reproduces every embedded reference value.
 *
 * Catalogue algorithms check four fixed inputs (the empty string, "123456789", all 256 byte values, and a 1 KiB pattern); the two large inputs are regenerated with a byte-at-a-time loop, so no big array is embedded.  The references come from two independent engines that had to agree.
 *
 * Run once on your target toolchain -- it is the cheapest way to catch a compiler / endianness / width mismatch before trusting the output.
 */
int crc16_xmodem_self_test(void);

#ifndef CRCGLOT_NO_PROVENANCE
#ifndef CRCGLOT_PROVENANCE_T_DEFINED
#define CRCGLOT_PROVENANCE_T_DEFINED
typedef struct {
    const char *algorithm;
    const char *target;
    const char *variant;
    const char *comment;
    const char *symbol;
    const char *naming;
} crcglot_provenance_t;
#endif
extern const crcglot_provenance_t crc16_xmodem_provenance;
#endif

#ifdef __cplusplus
}
#endif

#endif /* CRC16_XMODEM_H */
