/* crc16-xmodem -- XMODEM, ZMODEM, ACORN, LTE
 * Parameters: width=16, poly=0x1021, init=0x0000, refin=false, refout=false, xorout=0x0000.
 * check: crc16_xmodem(data, len) over "123456789" == 0x31C3
 *
 * Streaming (init -> update -> finalize); update may be called any
 * number of times over successive chunks of the message:
 *
 *     uint16_t s = crc16_xmodem_init();
 *     s = crc16_xmodem_update(s, chunk, chunk_len);
 *     uint16_t crc = crc16_xmodem_finalize(s);
 *
 * One-shot: crc16_xmodem(data, len)
 * Verify:   crc16_xmodem_self_test() returns 0 on success; run it once on your
 *           toolchain to catch a compiler / endianness mismatch.
 *
 * Generated by crcglot from reveng/crc16-xmodem -- a verified reference implementation.
 * Reproduce with crcglot:
 *     algorithm: crc16-xmodem
 *     target:    c
 *     variant:   bitwise
 *     comment:   plain
 *     symbol:    crc16_xmodem
 *     naming:    snake
 */
#include "crc16_xmodem.h"

uint16_t crc16_xmodem_init(void) {
    return 0x0000U;
}

uint16_t crc16_xmodem_update(uint16_t state, const uint8_t *data, size_t len) {
    uint16_t crc = state;
    for (size_t i = 0; i < len; i++) {
        crc ^= (uint16_t)data[i] << 8;
        for (int j = 0; j < 8; j++) {
            if ((crc & 0x8000U) != 0U) {
                crc = (crc << 1) ^ 0x1021U;
            } else {
                crc <<= 1;
            }
            crc &= 0xFFFFU;
        }
    }
    return crc;
}

uint16_t crc16_xmodem_finalize(uint16_t state) {
    return state;
}

uint16_t crc16_xmodem(const uint8_t *data, size_t len) {
    return crc16_xmodem_finalize(crc16_xmodem_update(crc16_xmodem_init(), data, len));
}

int crc16_xmodem_self_test(void) {
    static const uint8_t kCheckInput[] = "123456789";
    int failed = 0;
    if (crc16_xmodem(kCheckInput, 0) != 0x0000U) {
        failed = 1;
    }
    if (crc16_xmodem(kCheckInput, 9) != 0x31C3U) {
        failed = 1;
    }
    {
        uint16_t s = crc16_xmodem_init();
        for (unsigned int i = 0U; i < 256U; i++) {
            uint8_t b = (uint8_t)i;
            s = crc16_xmodem_update(s, &b, 1);
        }
        if (crc16_xmodem_finalize(s) != 0x7E55U) {
            failed = 1;
        }
    }
    {
        uint16_t s = crc16_xmodem_init();
        for (unsigned int i = 0U; i < 1024U; i++) {
            uint8_t b = (uint8_t)(((i * 167U) + 13U) & 0xFFU);
            s = crc16_xmodem_update(s, &b, 1);
        }
        if (crc16_xmodem_finalize(s) != 0x97E5U) {
            failed = 1;
        }
    }
    return (failed != 0) ? 1 : 0;
}

#ifndef CRCGLOT_NO_PROVENANCE
const crcglot_provenance_t crc16_xmodem_provenance = {
    .algorithm = "crc16-xmodem",
    .target    = "c",
    .variant   = "bitwise",
    .comment   = "plain",
    .symbol    = "crc16_xmodem",
    .naming    = "snake",
};
#endif
